[project]
name = "ivy"
version = "1.0.0"
description = "A Python template for an IoT node automation software supporting over-the air configuration and software updates"
requires-python = ">=3.10,<4.0"
authors = [{ name = "Moritz Makowski", email = "moritz.makowski@tum.de" }]
dependencies = [
  "python-dotenv>=1.0.0",
  "filelock>=3.13.1",
  "pytest>=7.4.4",
  "pydantic>=2.5.3",
  "psutil>=5.9.7",
  "paho-mqtt>=1.6.1",
  "tenta>=0.1.4",
  "typing-extensions>=4.6.3",
  "click>=8.1.7",
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
license = { text = "MIT" }
readme = "README.md"

[project.urls]
repository = "https://github.com/tum-esm/ivy"
documentation = "https://ivy.pages.dev/"

[project.optional-dependencies]
dev = [
  "mypy>=1.8.0",
  "jsonref>=1.1.0",
  "types-psutil>=5.9.5.20240106",
  "setuptools>=69.0.3",
  "pytest-cov>=4.1.0",
  "types-paho-mqtt>=1.6.0.20240106",
  "docstring-parser>=0.11",
]
[tool.pdm]
distribution = false

[tool.setuptools]
packages = []

[tool.pytest.ini_options]
markers = [
  "ci: can be run in any environment",
  "integration: can only be run on a configured system",
  "version_change: will run before switching to a new version",
]

[tool.mypy]
implicit_reexport = true
plugins = ["pydantic.mypy"]
strict = true
warn_unused_ignores = false

[tool.yapf]
based_on_style = "facebook"
coalesce_brackets = true
each_dict_entry_on_separate_line = false
spaces_around_subscript_colon = true
split_before_dict_set_generator = true
column_limit = 90

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["jsonref"]
