[project]
name = "ivy-seed"
version = "0.1.0"
description = "A Python template for an IoT node automation software supporting over-the air configuration and software updates"
authors = [
    { name = "Moritz Makowski", email = "moritz@dostuffthatmatters.dev" },
]
dependencies = [
    "python-dotenv>=1.0.0",
    "filelock>=3.13.1",
    "pytest>=7.4.4",
    "pydantic>=2.5.3",
    "psutil>=5.9.7",
    "tenta>=0.1.2",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
dev = [
    "mypy>=1.8.0",
    "pydoc-markdown>=4.8.2",
    "jsonref>=1.1.0",
    "types-psutil>=5.9.5.20240106",
    "setuptools>=69.0.3",
    "pytest-cov>=4.1.0",
]
[tool.pdm]
package-type = "application"

[tool.setuptools]
packages = []

[tool.pytest.ini_options]
markers = [
    "ci: can be run in any environment",
    "integration: can only be run on a configured system",
    "version_change: will run before switching to a new version",
]

[tool.mypy]
strict = true
implicit_reexport = true
plugins = ["pydantic.mypy"]

[tool.yapf]
based_on_style = "facebook"
coalesce_brackets = true
split_before_dict_set_generator = true
each_dict_entry_on_separate_line = false
spaces_around_subscript_colon = true

[[tool.mypy.overrides]]
module = ["jsonref"]
ignore_missing_imports = true
