[project]
name = "ivy"
version = "1.0.0"
description = "A Python boilerplate for an IoT node data acqusition system supporting remote configuration and software updates"
requires-python = ">=3.10,<4.0"
authors = [{ name = "Moritz Makowski", email = "moritz.makowski@tum.de" }]
dependencies = [
  "python-dotenv>=1.0.1",
  "filelock>=3.13.4",          # TODO: upgrade
  "pytest>=8.1.1",             # TODO: upgrade
  "psutil>=5.9.8",             # TODO: upgrade
  "typing-extensions>=4.11.0",
  "click>=8.1.7",              # TODO: can we simply do argparse?
  "tenta>=0.1.5",
  "tum-esm-utils>=2.2.0",
  "pydantic>=2.8.2",
]
classifiers = [
  "License :: OSI Approved :: GNU General Public License (GPL)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
license = { text = "GPL-3.0" }
readme = "README.md"

[project.urls]
repository = "https://github.com/tum-esm/ivy"
documentation = "https://ivy-docs.pages.dev/"

[project.optional-dependencies]
dev = [
  "mypy>=1.9.0",
  "jsonref>=1.1.0",
  "types-psutil>=5.9.5.20240316",
  "setuptools>=69.5.1",
  "pytest-cov>=5.0.0",
  "types-paho-mqtt>=1.6.0.20240321",
  "docstring-parser>=0.16",
]
[tool.pdm]
distribution = false

[tool.setuptools]
packages = []

[tool.pytest.ini_options]
markers = [
  "ci: can be run in any environment",
  "integration: can only be run on a configured system",
  "version_change: will run before switching to a new version",
]

[tool.mypy]
implicit_reexport = true
plugins = ["pydantic.mypy"]
strict = true
warn_unused_ignores = false

[tool.yapf]
based_on_style = "facebook"
coalesce_brackets = true
each_dict_entry_on_separate_line = false
spaces_around_subscript_colon = true
split_before_dict_set_generator = true
column_limit = 90

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["jsonref"]
