[tool.poetry]
name = "ivy-seed"
version = "0.1.0"
description = ""
authors = ["Moritz Makowski <moritz@dostuffthatmatters.dev>"]
repository = "https://github.com/tum-esm/ivy-seed"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11,<=3.12"
python-dotenv = "^1.0.0"
filelock = "^3.13.1"
pytest = "^7.4.3"
pydantic = "^2.5.2"
psutil = "^5.9.6"

[tool.pytest.ini_options]
markers = [
    "ci: can be run in any environment",
    "integration: can only be run on a configured system",
    "version_change: will run before switching to a new version",
]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.0"
pydoc-markdown = "^4.8.2"
jsonref = "^1.1.0"
types-psutil = "^5.9.5.17"

[tool.mypy]
strict = true
implicit_reexport = true
no_warn_unused_ignores = true
plugins = ["pydantic.mypy"]

[tool.yapf]
based_on_style = "facebook"
coalesce_brackets = true
split_before_dict_set_generator = true
each_dict_entry_on_separate_line = false
spaces_around_subscript_colon = true

[[tool.mypy.overrides]]
module = ["jsonref"]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
