[tool.poetry]
name = "ivy-seed"
version = "0.1.0"
description = ""
authors = ["Moritz Makowski <moritz@dostuffthatmatters.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
python-dotenv = "^1.0.0"
filelock = "^3.13.1"
pytest = "^7.4.3"
pydantic = "^2.5.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.0"

[tool.mypy]
strict = true
implicit_reexport = true
no_warn_unused_ignores = true
plugins = ["pydantic.mypy"]

[tool.yapf]
based_on_style = "facebook"
coalesce_brackets = true
split_before_dict_set_generator = true
each_dict_entry_on_separate_line = false
spaces_around_subscript_colon = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
