name: "branch-on-tag"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  branch-on-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          BRANCH_LABEL=$(echo "${{ github.ref_name }}" | cut -d. -f1-2)
          echo "BRANCH_LABEL = $BRANCH_LABEL"
          echo "BRANCH_LABEL = $BRANCH_LABEL" >> $GITHUB_ENV
          git remote -v
