name: "branch-on-tag"

on:
  push:
    tags:
      - "v*.*.*"

permissions: write-all

jobs:
  branch-on-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create branch from tag
        run: |
          BRANCH_NAME="docs-$(echo ${{ github.ref_name }} | cut -d. -f1-2)"
          echo "BRANCH_NAME = $BRANCH_NAME"
          git checkout -b $BRANCH_NAME || git checkout $BRANCH_NAME
          git reset --hard ${{ github.ref_name }}
          git push origin $BRANCH_NAME --force
