name: "deploy docs on tag"

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          DOCS_DEPLOY_VERSION=$(echo "${{ github.ref_name }}" | cut -d. -f1-2)
          echo "DOCS_DEPLOY_VERSION = $DOCS_DEPLOY_VERSION"
