name: "test"
on:
  push:
    branches:
      - never
  pull_request:
    branches:
      - never

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"

      - name: Install dependencies
        run: pip install ".[dev]"

      - name: Run pytests
        run: |
          pytest --verbose -m "ci" --cov=src tests/
